### ISSUE TITLE
[1.12.2-0.0.4] - `/profile c 10` returns Could not process command (NPE)

### ISSUE THREAD

**Issue by JaSpr** [MinimallyCorrect/TickProfiler#100]
When running `/profile c 10`, the following error shows up in chat: `An Unknown error occurred while attempting to run this command` and the following is logged to the server console:
```
[22:20:54] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: profile c 10
java.lang.NullPointerException: null
        at org.minimallycorrect.tickprofiler.minecraft.profiling.EntityCountingProfiler.start(EntityCountingProfiler.java:34) ~[EntityCountingProfiler.class:?]
        at org.minimallycorrect.tickprofiler.minecraft.profiling.Profile.start(Profile.java:52) ~[Profile.class:?]
        at org.minimallycorrect.tickprofiler.minecraft.commands.ProfileCommand.process(ProfileCommand.java:71) ~[ProfileCommand.class:?]
        at org.minimallycorrect.tickprofiler.minecraft.commands.ProfileCommand.processCommand(ProfileCommand.java:30) ~[ProfileCommand.class:?]
        at org.minimallycorrect.tickprofiler.minecraft.commands.Command.func_184881_a(Command.java:45) ~[Command.class:?]
        at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:82) ~[CommandOverride.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:528) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by LunNova** [comment]
https://github.com/MinimallyCorrect/TickProfiler/blob/8656b0db8c886312ab364ecd013ae62e3f3a970e/src/main/java/org/minimallycorrect/tickprofiler/minecraft/profiling/EntityCountingProfiler.java#L34

world here is null, which shouldn't happen.

What mods are you running? Are you using sponge?

**Comment by JaSpr** [comment]
We are NOT using Sponge.  We are running ATM3, v5.9.6b, which has many, many mods in it.

I can likely get you a full list of mods later this evening.

**Comment by JaSpr** [comment]
We're using RFTools dimensions and some space mod as well, each of which add dimensions, and I can see from line 33 that `world` is pulled from `worldList`.  It is quite possible that there is an entry in `worldList` that is null, possibly caused by one of these other mods.  I feel that TickProfiler should skip any worlds in the world list that are null.

**Comment by JaSpr** [comment]
List of all mods: https://gist.github.com/JaSpr/1bc5e70433c88bb891cb6f95fc80fe5c

**Comment by JaSpr** [comment]
Unfortunately, that error was for `/profile c 10`, and the blank list is for `/profile e 10`.  

When I run `/profile e 10` I get the blank response (like in the screenshot in the initial request).  There is absolutely no log saying why it returned empty.

when I run `/profile c 10` I get `An Unknown error occurred while attempting to run this command`, probably because of the NPE in the stack trace.  

Should I split this into two separate tickets?

**Comment by JaSpr** [comment]
I have updated this ticket to be for the `/profile c` issue, while the `/profile e` issue can be found at #101

**Comment by generrosity** [comment]
Interesting - I restarted my server this morning and got this same /profile c "unknown error" / "null pointer" issue. Only change was to remove the Unloader mod. Previously working yesterday while helping someone else diagnose their own server performance issues. Restart has not yet helped.

**Comment by Shybella** [comment]
Any updates on this? 

Is there a reason why this wouldn't work with Sponge? I can report this to Sponge.
