### ISSUE TITLE
[BUG] Saving profile.txt

### ISSUE THREAD

**Issue by Komoden** [MinimallyCorrect/TickProfiler#27]
From my server log (yes it's a windows machine)

[17:13:47] [TickProfiler/ERROR] [TickProfiler/]: Failed to save periodic profiling data to .\ibkiworld1710\computer\63\profile.txt
java.io.FileNotFoundException: .\ibkiworld1710\computer\63\profile.txt (The system cannot find the path specified)
    at java.io.FileOutputStream.open(Native Method) ~[?:1.7.0_71]
    at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.7.0_71]
    at com.google.common.io.Files$FileByteSink.openStream(Files.java:201) ~[minecraft_server.1.7.10.jar:?]
    at com.google.common.io.Files$FileByteSink.openStream(Files.java:189) ~[minecraft_server.1.7.10.jar:?]
    at com.google.common.io.ByteSink$AsCharSink.openStream(ByteSink.java:163) ~[minecraft_server.1.7.10.jar:?]
    at com.google.common.io.CharSink.write(CharSink.java:110) ~[minecraft_server.1.7.10.jar:?]
    at com.google.common.io.Files.write(Files.java:477) ~[minecraft_server.1.7.10.jar:?]
    at nallar.tickprofiler.minecraft.TickProfiler$ProfilingScheduledTickHandler$1.run(TickProfiler.java:184) [TickProfiler$ProfilingScheduledTickHandler$1.class:?]
    at nallar.tickprofiler.minecraft.profiling.EntityTickProfiler$1.run(EntityTickProfiler.java:107) [EntityTickProfiler$1.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]

**Comment by LunNova** [comment]
Looks like a configuration error - the path you configured to save profiling data to doesn't exist.
