### ISSUE TITLE
Profile command is not working

### ISSUE THREAD

**Issue by Noire86** [MinimallyCorrect/TickProfiler#34]
Sending this on using command "profile":

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_71]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_71]
        at nallar.tickprofiler.minecraft.commands.ProfileCommand.process(ProfileCommand.java:42) ~[ProfileCommand.class:?]
        at nallar.tickprofiler.minecraft.commands.ProfileCommand.processCommand(ProfileCommand.java:32) ~[ProfileCommand.class:?]
        at nallar.tickprofiler.minecraft.commands.Command.func_71515_b(Command.java:42) ~[Command.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:99) [z.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:51) [CraftSimpleCommandMap.class:1.7.10-1614.195]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchVanillaCommand(CraftServer.java:733) [CraftServer.class:1.7.10-1614.195]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:701) [CraftServer.class:1.7.10-1614.195]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:473) [lt.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]

**Comment by LunNova** [comment]
Thanks for the report.

I recently refactored the profiling command handler to simplify it, and managed to break it so it crashed instead of showing the usage message if you didn't pass any arguments.

Fixed in build 12 on jenkin/commit d6b916ff2f82aa5f6

**Comment by Noire86** [comment]
Thanks!
