### ISSUE TITLE
Command is not working (Again)

### ISSUE THREAD

**Issue by Noire86** [MinimallyCorrect/TickProfiler#35]
Using build 12 from jenkins:

profile -e

java.lang.RuntimeException
        at nallar.tickprofiler.minecraft.commands.ProfileCommand.process(ProfileCommand.java:47) ~[ProfileCommand.class:?]
        at nallar.tickprofiler.minecraft.commands.ProfileCommand.processCommand(ProfileCommand.java:32) ~[ProfileCommand.class:?]
        at nallar.tickprofiler.minecraft.commands.Command.func_71515_b(Command.java:42) ~[Command.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:99) [z.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:51) [CraftSimpleCommandMap.class:1.7.10-1614.193]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchVanillaCommand(CraftServer.java:733) [CraftServer.class:1.7.10-1614.193]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:701) [CraftServer.class:1.7.10-1614.193]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:473) [lt.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]

**Comment by LunNova** [comment]
It's just `/profile e`, not `/profile -e`.

It should've shown you the usage, not crashed.

**Comment by LunNova** [comment]
Fixed in bcaacb406bc70ce. Bug introduced by the same refactoring as the last issue (#34).
