### ISSUE TITLE
Crash NoClassDefFoundError: org/json/JSONException

### ISSUE THREAD

**Issue by BlayzerQ** [MinimallyCorrect/TickProfiler#53]
Thermos, 1.7.10. TickProfiler 32 build.

 java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
 Caused by: java.lang.NoClassDefFoundError: org/json/JSONException
    at me.nallar.javapatcher.patcher.Patcher.readPatchesFromXmlInputStream(Patcher.java:129)
    at nallar.tickprofiler.minecraft.CoreMod.injectData(CoreMod.java:28)
    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:120)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    ... 6 more
 Caused by: java.lang.ClassNotFoundException: org.json.JSONException
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:112)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 11 more

**Comment by LunNova** [comment]
`org/json/JSONException.class` is present in `TickProfiler-1.7.10.jenkins.32.jar`, so that error is quite odd.

Can you try downloading the jar again? I suspect it might be a corrupt jar. The size should be `2,564,161` bytes and the md5 hash should be `aaa1ff0ca46dde989268db29bc0a9cc8`.

Failing that, if another mod or library you are using contains an invalid `org.json.JSONException` or a coremod's transformer breaks `org.json.JSONException` it could cause this error.

**Comment by BlayzerQ** [comment]
MD5 correct: http://ssmaker.ru/ec3c0eba.png
i`am download this file again, crash still.

**Comment by LunNova** [comment]
Can you link to the modpack you're using, if it's public?

**Comment by BlayzerQ** [comment]
This is my modpak, I collected it myself (I can give this modpack (Server side, if this need)).
I early used version 39 (2014 year), but in a thermos with him there were problems. I decided to update events, but here this problem.

**Comment by BlayzerQ** [comment]
I have 3 modpacks, on 3 of them this problem. I think that the problem is related to the server core (Thermos).

**Comment by LunNova** [comment]
Launching with `Thermos-1.7.10-1614-server.jar` doesn't run into that error for me.

What thermos version are you using?

Can you run `grep -ri org/json/jsonexception mods` and see if it finds any files other than TickProfiler? It'll list any mods containing that class. Maybe there is another mod you're using which contains its own version of that class. Could also try `grep -ri org/json/jsonexception libraries` in case there's something in your libraries folder.

**Comment by BlayzerQ** [comment]
I`am use Thermos-1.7.10-1614 (56 build)
grep say:
Binary file mods/1.7.10/TickProfiler-1.7.10.jenkins.32.jar matches
nothing else. At the libraries nothing.

**Comment by LunNova** [comment]
I wasn't able to replicate the issue, but I've tried a possible fix in TickProfiler build 33: https://github.com/nallar/ModPatcher/commit/cf7776b323a2741dd3ac25d0060e6ce3c0054cd3

**Comment by BlayzerQ** [comment]
It did not help :(

**Comment by BlayzerQ** [comment]
I deleted all mods except TickProfiler.
Crash. I'll try to redownload the server core.

**Comment by BlayzerQ** [comment]
Oook, i download latest Thermos build (58), redownload libraries and core.
All works!

**Comment by LunNova** [comment]
Okay, I'll close this. Not sure why it wasn't working but it is now so it doesn't matter! :)
