### ISSUE TITLE
/profile e - show nothing

### ISSUE THREAD

**Issue by BlayzerQ** [MinimallyCorrect/TickProfiler#54]
When i use /profile e, after 30 seconds profile show nothing.
http://ssmaker.ru/1300aca6.png

Thermos, 1.7.10. Last build Thermos and TickProfiler.

**Comment by BlayzerQ** [comment]
On server start, at log:
[14:58:01] [main/INFO] [JavaPatcher/]: me.nallar.javapatcher.patcher.Patcher$ClassPatchDescriptor@1d6f523
[14:58:01] [main/ERROR] [JavaPatcher/]: Error patching func_72939_s in net.minecraft.world.World with insertCodeBefore
java.lang.RuntimeException: java.io.EOFException
    at javassist.CtClassType.getClassFile2(CtClassType.java:205) ~[CtClassType.class:?]
    at javassist.CtClassType.makeFieldCache(CtClassType.java:848) ~[CtClassType.class:?]
    at javassist.CtClassType.getMembers(CtClassType.java:839) ~[CtClassType.class:?]
    at javassist.CtClassType.getDeclaredField2(CtClassType.java:973) ~[CtClassType.class:?]
    at javassist.CtClassType.getField2(CtClassType.java:927) ~[CtClassType.class:?]
    at javassist.CtClassType.getField(CtClassType.java:908) ~[CtClassType.class:?]
    at javassist.CtClass.getField(CtClass.java:798) ~[CtClass.class:?]
    at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:282) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:887) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:844) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Expr.accept(Expr.java:68) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:834) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Expr.accept(Expr.java:68) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:660) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.CodeGen.compileBooleanExpr(CodeGen.java:236) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:384) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.Javac.compileStmnt(Javac.java:569) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.CtBehavior.insertBefore(CtBehavior.java:754) ~[CtBehavior.class:?]
    at javassist.CtBehavior.insertBefore(CtBehavior.java:734) ~[CtBehavior.class:?]
    at me.nallar.javapatcher.patcher.Patches.insertCodeBefore(Patches.java:931) ~[Patches.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at me.nallar.javapatcher.patcher.Patcher$PatchMethodDescriptor.run(Patcher.java:427) [Patcher$PatchMethodDescriptor.class:?]
    at me.nallar.javapatcher.patcher.Patcher$PatchMethodDescriptor.run(Patcher.java:397) [Patcher$PatchMethodDescriptor.class:?]
    at me.nallar.javapatcher.patcher.Patcher$ClassPatchDescriptor.runPatches(Patcher.java:522) [Patcher$ClassPatchDescriptor.class:?]
    at me.nallar.javapatcher.patcher.Patcher.patch(Patcher.java:212) [Patcher.class:?]
    at me.nallar.modpatcher.ModPatcher.postSrgTransformationHook(ModPatcher.java:82) [ModPatcher.class:?]
    at me.nallar.modpatcher.ModPatcher.transform(ModPatcher.java:121) [ModPatcher.class:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_91]
    at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_91]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763) [?:1.8.0_91]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_91]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_91]
    at java.lang.Class.getDeclaredMethods0(Native Method) [?:1.8.0_91]
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_91]
    at java.lang.Class.privateGetMethodRecursive(Class.java:3048) [?:1.8.0_91]
    at java.lang.Class.getMethod0(Class.java:3018) [?:1.8.0_91]
    at java.lang.Class.getMethod(Class.java:1784) [?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:132) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [Thermos.jar:1.7.10-1614.58]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [Thermos.jar:1.7.10-1614.58]
Caused by: java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:392) ~[?:1.8.0_91]
    at javassist.bytecode.ClassFile.read(ClassFile.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.bytecode.ClassFile.<init>(ClassFile.java:124) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.CtClassType.getClassFile2(CtClassType.java:192) ~[CtClassType.class:?]
    ... 61 more
[14:58:01] [main/ERROR] [JavaPatcher/]: Error patching updateEntities_withProfiling in net.minecraft.world.World with replaceMethodCall
java.lang.RuntimeException: java.io.EOFException
    at javassist.CtClassType.getClassFile2(CtClassType.java:205) ~[CtClassType.class:?]
    at javassist.CtClassType.makeFieldCache(CtClassType.java:848) ~[CtClassType.class:?]
    at javassist.CtClassType.getMembers(CtClassType.java:839) ~[CtClassType.class:?]
    at javassist.CtClassType.getDeclaredField2(CtClassType.java:973) ~[CtClassType.class:?]
    at javassist.CtClassType.getField2(CtClassType.java:927) ~[CtClassType.class:?]
    at javassist.CtClassType.getField(CtClassType.java:908) ~[CtClassType.class:?]
    at javassist.CtClass.getField(CtClass.java:798) ~[CtClass.class:?]
    at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:282) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:887) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:844) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Expr.accept(Expr.java:68) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:834) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Expr.accept(Expr.java:68) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:834) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Expr.accept(Expr.java:68) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:834) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Expr.accept(Expr.java:68) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:660) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.Javac.compileStmnt(Javac.java:569) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.expr.MethodCall.replace(MethodCall.java:235) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at me.nallar.javapatcher.patcher.Patches$6.edit(Patches.java:660) ~[Patches$6.class:?]
    at javassist.expr.ExprEditor.loopBody(ExprEditor.java:192) ~[ExprEditor.class:?]
    at javassist.expr.ExprEditor.doit(ExprEditor.java:91) ~[ExprEditor.class:?]
    at javassist.CtBehavior.instrument(CtBehavior.java:712) ~[CtBehavior.class:?]
    at me.nallar.javapatcher.patcher.Patches.replaceMethodCall(Patches.java:636) ~[Patches.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at me.nallar.javapatcher.patcher.Patcher$PatchMethodDescriptor.run(Patcher.java:427) [Patcher$PatchMethodDescriptor.class:?]
    at me.nallar.javapatcher.patcher.Patcher$PatchMethodDescriptor.run(Patcher.java:397) [Patcher$PatchMethodDescriptor.class:?]
    at me.nallar.javapatcher.patcher.Patcher$ClassPatchDescriptor.runPatches(Patcher.java:522) [Patcher$ClassPatchDescriptor.class:?]
    at me.nallar.javapatcher.patcher.Patcher.patch(Patcher.java:212) [Patcher.class:?]
    at me.nallar.modpatcher.ModPatcher.postSrgTransformationHook(ModPatcher.java:82) [ModPatcher.class:?]
    at me.nallar.modpatcher.ModPatcher.transform(ModPatcher.java:121) [ModPatcher.class:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_91]
    at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_91]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763) [?:1.8.0_91]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_91]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_91]
    at java.lang.Class.getDeclaredMethods0(Native Method) [?:1.8.0_91]
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_91]
    at java.lang.Class.privateGetMethodRecursive(Class.java:3048) [?:1.8.0_91]
    at java.lang.Class.getMethod0(Class.java:3018) [?:1.8.0_91]
    at java.lang.Class.getMethod(Class.java:1784) [?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:132) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [Thermos.jar:1.7.10-1614.58]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [Thermos.jar:1.7.10-1614.58]
Caused by: java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:392) ~[?:1.8.0_91]
    at javassist.bytecode.ClassFile.read(ClassFile.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.bytecode.ClassFile.<init>(ClassFile.java:124) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.CtClassType.getClassFile2(CtClassType.java:192) ~[CtClassType.class:?]
    ... 70 more
[14:58:01] [main/ERROR] [JavaPatcher/]: Error patching updateEntities_withProfiling in net.minecraft.world.World with replaceMethodCall
java.lang.RuntimeException: java.io.EOFException
    at javassist.CtClassType.getClassFile2(CtClassType.java:205) ~[CtClassType.class:?]
    at javassist.CtClassType.makeFieldCache(CtClassType.java:848) ~[CtClassType.class:?]
    at javassist.CtClassType.getMembers(CtClassType.java:839) ~[CtClassType.class:?]
    at javassist.CtClassType.getDeclaredField2(CtClassType.java:973) ~[CtClassType.class:?]
    at javassist.CtClassType.getField2(CtClassType.java:927) ~[CtClassType.class:?]
    at javassist.CtClassType.getField(CtClassType.java:908) ~[CtClassType.class:?]
    at javassist.CtClass.getField(CtClass.java:798) ~[CtClass.class:?]
    at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:282) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:887) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:844) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Expr.accept(Expr.java:68) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:834) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Expr.accept(Expr.java:68) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:834) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Expr.accept(Expr.java:68) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:834) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Expr.accept(Expr.java:68) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:660) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.compiler.Javac.compileStmnt(Javac.java:569) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.expr.MethodCall.replace(MethodCall.java:235) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at me.nallar.javapatcher.patcher.Patches$6.edit(Patches.java:660) ~[Patches$6.class:?]
    at javassist.expr.ExprEditor.loopBody(ExprEditor.java:192) ~[ExprEditor.class:?]
    at javassist.expr.ExprEditor.doit(ExprEditor.java:91) ~[ExprEditor.class:?]
    at javassist.CtBehavior.instrument(CtBehavior.java:712) ~[CtBehavior.class:?]
    at me.nallar.javapatcher.patcher.Patches.replaceMethodCall(Patches.java:636) ~[Patches.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at me.nallar.javapatcher.patcher.Patcher$PatchMethodDescriptor.run(Patcher.java:427) [Patcher$PatchMethodDescriptor.class:?]
    at me.nallar.javapatcher.patcher.Patcher$PatchMethodDescriptor.run(Patcher.java:397) [Patcher$PatchMethodDescriptor.class:?]
    at me.nallar.javapatcher.patcher.Patcher$ClassPatchDescriptor.runPatches(Patcher.java:522) [Patcher$ClassPatchDescriptor.class:?]
    at me.nallar.javapatcher.patcher.Patcher.patch(Patcher.java:212) [Patcher.class:?]
    at me.nallar.modpatcher.ModPatcher.postSrgTransformationHook(ModPatcher.java:82) [ModPatcher.class:?]
    at me.nallar.modpatcher.ModPatcher.transform(ModPatcher.java:121) [ModPatcher.class:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_91]
    at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_91]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763) [?:1.8.0_91]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_91]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_91]
    at java.lang.Class.getDeclaredMethods0(Native Method) [?:1.8.0_91]
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_91]
    at java.lang.Class.privateGetMethodRecursive(Class.java:3048) [?:1.8.0_91]
    at java.lang.Class.getMethod0(Class.java:3018) [?:1.8.0_91]
    at java.lang.Class.getMethod(Class.java:1784) [?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:132) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [Thermos.jar:1.7.10-1614.58]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [Thermos.jar:1.7.10-1614.58]
Caused by: java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:392) ~[?:1.8.0_91]
    at javassist.bytecode.ClassFile.read(ClassFile.java:777) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.bytecode.ClassFile.<init>(ClassFile.java:124) ~[TickProfiler-1.7.10.jenkins.33.jar:?]
    at javassist.CtClassType.getClassFile2(CtClassType.java:192) ~[CtClassType.class:?]
    ... 70 more

**Comment by LunNova** [comment]
A similar issue to #43. I'll need to backport those changes in ModPatcher for 1.7.10 to fix it.

**Comment by BlayzerQ** [comment]
That is, it is not to fix?

**Comment by LunNova** [comment]
I will fix it, when I have time.

**Comment by BlayzerQ** [comment]
Ok, Thanks!

**Comment by LunNova** [comment]
https://github.com/nallar/ModPatcher/commit/86fa197856182c8efd9afec0f8de01a3dfbaa121 should fix it. 

It's in build 34.

**Comment by BlayzerQ** [comment]
[01:05:37] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.RuntimeException: java.lang.IllegalStateException
    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:138) ~[Thermos.jar:1.7.10-1614.58]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [Thermos.jar:1.7.10-1614.58]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [Thermos.jar:1.7.10-1614.58]
Caused by: java.lang.IllegalStateException
    at java.util.HashMap$HashIterator.remove(HashMap.java:1441) ~[?:1.8.0_91]
    at me.nallar.modpatcher.LaunchClassLoaderUtil.removeRedundantExclusions(LaunchClassLoaderUtil.java:303) ~[TickProfiler-1.7.10.jenkins.34.jar:?]
    at me.nallar.modpatcher.LaunchClassLoaderUtil.removeRedundantExclusions(LaunchClassLoaderUtil.java:292) ~[TickProfiler-1.7.10.jenkins.34.jar:?]
    at me.nallar.modpatcher.ModPatcherSetup.initialised(ModPatcherSetup.java:33) ~[ModPatcherSetup.class:?]
    at me.nallar.modpatcher.ModPatcherSetup.injectData(ModPatcherSetup.java:18) ~[ModPatcherSetup.class:?]
    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:133) ~[Thermos.jar:1.7.10-1614.58]
    ... 8 more
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:498)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:28)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Runtime.exit(Runtime.java:107)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.System.exit(System.java:971)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[01:05:37] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     ... 6 more

**Comment by LunNova** [comment]
Another attempt in build 35. https://github.com/nallar/ModPatcher/commit/fd34e6d42b5d9de3edf3b4c4e5b1dee0057a2ea6

**Comment by BlayzerQ** [comment]
All right! It works. Thanks!
