### ISSUE TITLE
/profile e shows no results

### ISSUE THREAD

**Issue by DreiPixel** [MinimallyCorrect/TickProfiler#55]
hello there, im trying to use the TickProfiler but the Result screen is empty

our server is using Minecraft 1.10.2 and Forge 12.18.1.2076

if you need more information tell me

**Comment by LunNova** [comment]
Please upload your FML log file.

Also, make sure you are running /profile e while at least one user is online. It may report nothing if no users are online, as the world isn't ticked after a while with no users and no forced chunks.

**Comment by DreiPixel** [comment]
i used the command while we had some players on the server and we use server sided chunkloader for chunkloading.

**Comment by DreiPixel** [comment]
https://www.dropbox.com/s/87s9vml00kbzwhv/fml-server-latest.log?dl=0 heres the log file

**Comment by LunNova** [comment]
Cause:

```
[10:55:50] [main/TRACE] [ModPatcher/]: Adding file:/usr/home/minecraft/bbqserver/mods/ModPatcher.jlib to classloader
[10:55:50] [main/TRACE] [ModPatcher/]: Loaded class: class me.nallar.modpatcher.ModPatcherLoadHook
[10:55:50] [main/INFO] [ModPatcher/]: Loaded ModPatcher. Version: 1.10.2.5 API version: 1
[10:55:50] [main/INFO] [ModPatcher/]: ModPatcher running under classloader net.minecraft.launchwrapper.LaunchClassLoader
[10:55:51] [main/ERROR] [ModPatcher/]: Failed to load MCP mappings
java.lang.NullPointerException
    at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_102]
    at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[?:1.8.0_102]
    at java.util.Scanner.<init>(Scanner.java:563) ~[?:1.8.0_102]
    at me.nallar.modpatcher.MCPMappings.loadSrg(MCPMappings.java:190) ~[ModPatcher.jlib:1.10.2-SNAPSHOT+Jenkins-b5.git-8e90a64715cae1de6604b2627062d3267aa90b58]
    at me.nallar.modpatcher.MCPMappings.<init>(MCPMappings.java:34) [ModPatcher.jlib:1.10.2-SNAPSHOT+Jenkins-b5.git-8e90a64715cae1de6604b2627062d3267aa90b58]
    at me.nallar.modpatcher.ModPatcherTransformer.<clinit>(ModPatcherTransformer.java:29) [ModPatcher.jlib:1.10.2-SNAPSHOT+Jenkins-b5.git-8e90a64715cae1de6604b2627062d3267aa90b58]
    at me.nallar.modpatcher.ModPatcher.getDefaultPatchesDirectory(ModPatcher.java:150) [ModPatcher.class:1.10.2-SNAPSHOT+Jenkins-b5.git-8e90a64715cae1de6604b2627062d3267aa90b58]
    at me.nallar.modpatcher.coremod.CoreMod.injectData(CoreMod.java:55) [ModPatcher-1.10.2-SNAPSHOT-coremod.jar:1.10.2-SNAPSHOT+Jenkins-b5.git-8e90a64715cae1de6604b2627062d3267aa90b58]
    at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:150) [forge-1.10.2-12.18.1.2076-universal.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-1.10.2-12.18.1.2076-universal.jar:?]
    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-1.10.2-12.18.1.2076-universal.jar:?]
```

Will fix in a few hours, at work right now.
