### ISSUE TITLE
java.lang.NoClassDefFoundError: org/json/JSONException

### ISSUE THREAD

**Issue by importnil** [MinimallyCorrect/TickProfiler#63]
TickProfiler-1.7.10.jenkins.37.jar;

```
[05:28:12] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[05:28:12] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[05:28:12] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[05:28:12] [main/INFO]: Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10 loading
[05:28:13] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_91, running on Linux:amd64:3.16.0-4-amd64, installed at /usr/lib/jvm/java-8-oracle/jre
[05:28:13] [main/INFO]: [pw.prok.imagine.ImagineLoadingPlugin:<clinit>:26]: Loading plugin initialized!
[05:28:13] [main/INFO]: [AppEng] Core Init
[05:28:15] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of CodeChickenLib, 1.1.3.140 is newer than request 1.1.3.138
[05:28:15] [main/WARN]: Found FastCraft coremod, skipping...
[05:28:15] [main/INFO]: Loading tweaker forestry.shade.javacheck.Java7Checker from forestry_1.7.10-4.2.16.64.jar
[05:28:15] [main/INFO]: [micdoodle8.mods.miccore.DepLoader$DepLoadInst:<init>:333]: MicdoodleCore searching for dependencies in mods file: /home/vadimyer/hitech/./mods
[05:28:15] [main/WARN]: The following coremods do not have a @MCVersion annotation. They may cause problems if this is not the correct version of Minecraft for them.
[05:28:15] [main/WARN]: Missing @MCVersion: codechicken.core.launch.CodeChickenCorePlugin  cofh.asm.LoadingPlugin  codechicken.core.launch.DepLoader  mrtjp.relocation.asm.RelocationPlugin  ic2.core.coremod.IC2core  micdoodle8.mods.miccore.MicdoodlePlugin  mrtjp.core.handler.CorePlugin  codechicken.nei.asm.NEICorePlugin  openblocks.OpenBlocksCorePlugin  openmods.core.OpenModsCorePlugin  codechicken.core.launch.DepLoader  nallar.tickprofiler.minecraft.CoreMod  
[05:28:15] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:28:15] [main/INFO]: Loading tweak class name forestry.shade.javacheck.Java7Checker
[05:28:15] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[05:28:15] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:28:15] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:28:15] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:15] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:15] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:15] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Loaded library EJML-core-0.26.jar.
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
[05:28:17] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[05:28:17] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class forestry.shade.javacheck.Java7Checker
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:28:17] [main/INFO]: ModPatcher running under classloader net.minecraft.launchwrapper.LaunchClassLoader
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: org/json/JSONException
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at me.nallar.javapatcher.patcher.Patcher.readPatchesFromXmlInputStream(Patcher.java:129)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at nallar.tickprofiler.minecraft.CoreMod.injectData(CoreMod.java:28)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:120)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 6 more
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: org.json.JSONException
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:112)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[05:28:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 11 more

```

**Comment by LunNova** [comment]
Can't replicate.

What's your mod list? Are you using a public mod pack?

Are you using a non-standard server jar (eg MCPC)?

**Comment by importnil** [comment]
Yes I'm using Thermos B58 (their latest build) with custom net/minecraft/launchwrapper and net/minecraft/server/1.7.10 from here: http://launcher.sashok724.net/download/servers/thermos1.7.10.zip

The reason behind patched Thermos.jar is using it along with our custom launcher that's from the author who patched Thermos.

**Comment by LunNova** [comment]
Put the org.json classes from TP in a library's jar (anything in the libraries folder which is actually loaded in your setup) as a workaround so they can be loaded, or fix your custom patched launcher not to exclude org.json. I can't see any reason why that needs to be classloader excluded.

Not a bug in TickProfiler, nothing I can change to fix this.

**Comment by importnil** [comment]
Thanks for the reply.
