### ISSUE TITLE
[1.12.1] Server is acting weird (Leaking and more)

### ISSUE THREAD

**Issue by UnPure** [MinimallyCorrect/TickProfiler#84]
Hey there.
While using TickProfiler on my sever, the server is starting to act weird and is producing **TONS** of log entrys about problems. As soon as i remove TickProfiler, its stopping.

**latest.log** https://pastebin.com/b5eDRmkP
**fml-junk-earlystartup.log** http://unpure-gaming.de/~minecraft/fml-junk-earlystartup.log

I had to upload the log to my own server because i dont know about any website that can host files that are 8MB with ~70k lines.

**TickProfiler:** 1.12-0.0.1
**Forge:** 14.22.0.2475
**Modlist:** http://upclan.de/modpack/info/

While the server is running with TickProfiler, that latest.log spams tons of entrys like

    [22:31:44] [Server thread/ERROR]: Failed to save chunk
    java.lang.NullPointerException: null

and this

    [20:28:15] [Server thread/ERROR]: Failed to save chunk
    java.lang.NullPointerException: null
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:334) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:171) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:270) [on.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:206) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

As soon as i remove TickProfiler, this spams stops completly.
Also the earlystartup log spams this:

    [22:48:36] [Server thread/DEBUG] [FML]: The world 35e436b (unpure) may have leaked: seen 2045 times.

Every ~45seconds its 5 times more.

**Comment by UnPure** [comment]
Ok nevermind. For some reason without TickProfiler that spams just delays.
After the server was running for ~10min. the spam started without TickProfiler.
Something else seems to cause these issues.

**Comment by LunNova** [comment]
Even though it's not caused by TickProfiler, If you do find out what was causing it please do comment here in case someone else runs into the same issue and finds your post.

[![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)](https://xkcd.com/979/)

**Comment by UnPure** [comment]
@nallar Thats the plan. Currently it seems like the mod CompactMachines is causing this issue. There are a few things that point to that mod. I reported it to the mod author and i'm currently trying to find something together with him. I will write more informations as soon as its clear.
btw i like that image and i know that feeling! :(
